receivers:
  otlp:
    protocols:
      # Coleta dados de trace via protocolo HTTP na porta 4318
      http:
        endpoint: "0.0.0.0:4318"
      # Coleta dados de trace via protocolo gRPC na porta 4317
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  debug:
    # Exporta os dados no console para fins de debug com nível detalhado
    verbosity: detailed

  otlp:
    # Envia traces diretamente ao Tempo via OTLP gRPC
    endpoint: "tempo:4319"
    tls:
      # Desativa TLS em ambiente local (sem HTTPS)
      insecure: true

  loki:
    # Exportador de logs configurado para enviar os logs diretamente ao Loki
    endpoint: "http://loki:3100/loki/api/v1/push"

service:
  pipelines:
    traces:
      # Define quais receivers são usados para receber os dados de trace
      receivers: [otlp]
      # Define para onde os dados serão exportados
      exporters: [otlp, debug]

    logs:
      # Pipeline de logs: recebe por OTLP e envia para console e Loki
      receivers: [otlp]
      exporters: [loki, debug]  
