receivers:
  otlp:
    protocols:
      # Coleta dados de trace via protocolo HTTP na porta 4318
      http:
        endpoint: "0.0.0.0:4318"
      # Coleta dados de trace via protocolo gRPC na porta 4317
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  debug:
    # Exporta os dados no console para fins de debug com nível detalhado
    verbosity: detailed

  otlp:
    # Envia os dados OTLP para outro destino (ex: Grafana Tempo)
    endpoint: "http://localhost:4317"
    tls:
      # Desabilita a verificação TLS (uso comum em ambientes locais)
      insecure: true

service:
  pipelines:
    traces:
      # Define quais receivers são usados para receber os dados de trace
      receivers: [otlp]
      # Define para onde os dados serão exportados
      exporters: [debug, otlp]
