global:
  # Define o intervalo padrão entre coletas de métricas
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    # Define os alvos estáticos que Prometheus deve monitorar
    static_configs:
      - targets: ['otel-collector:8889']  # Endpoint do OTEL Collector para métricas
